# Generated by Django 3.2.20 on 2023-07-23 20:38

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('start_date_time', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 7, 24, 20, 38, 52, 727737, tzinfo=utc)), django.core.validators.MaxValueValidator(datetime.datetime(2026, 7, 27, 20, 38, 52, 727808, tzinfo=utc))])),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('website_link', models.URLField(blank=True, max_length=250, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cover_image', models.ImageField(blank=True, default='../default_post_rgq6aq', null=True, upload_to='images/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
