# Generated by Django 3.2.20 on 2023-07-23 21:18

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20230723_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date_time',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 7, 24, 21, 18, 11, 703554, tzinfo=utc)), django.core.validators.MaxValueValidator(datetime.datetime(2026, 7, 27, 21, 18, 11, 703568, tzinfo=utc))]),
        ),
    ]
