# Generated by Django 3.2.20 on 2023-07-23 21:20

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_start_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date_time',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 7, 24, 21, 20, 7, 792405, tzinfo=utc)), django.core.validators.MaxValueValidator(datetime.datetime(2026, 7, 27, 21, 20, 7, 792419, tzinfo=utc))]),
        ),
    ]
