# Generated by Django 3.2.20 on 2023-07-26 16:09

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_start_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date_time',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 7, 27, 16, 9, 1, 905849, tzinfo=utc)), django.core.validators.MaxValueValidator(datetime.datetime(2026, 7, 30, 16, 9, 1, 905863, tzinfo=utc))]),
        ),
    ]
