# Generated by Django 3.2.20 on 2023-07-28 02:21

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_start_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, default='../default_post_ed2doq', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date_time',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 7, 29, 2, 21, 5, 199069, tzinfo=utc)), django.core.validators.MaxValueValidator(datetime.datetime(2026, 8, 1, 2, 21, 5, 199087, tzinfo=utc))]),
        ),
    ]
