# Generated by Django 3.2.20 on 2023-07-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='event',
        ),
    ]
