# Generated by Django 3.2.20 on 2023-07-22 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_taskcategory_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='idea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_items', to='todo.idea'),
        ),
    ]
