# Generated by Django 3.2.20 on 2023-07-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_taskcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='todos',
            field=models.ManyToManyField(blank=True, to='todo.Task'),
        ),
    ]
